In [10]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,])

In [13]:
arr

array([1, 2, 3, 4])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.full((4,2), 8)

array([[8, 8],
       [8, 8],
       [8, 8],
       [8, 8]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.arange(1,100, 9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [48]:
np.linspace(1, 10 , 7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [50]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9],[11,12,13]])

In [52]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [54]:
myarr.shape

(4, 3)

In [56]:
myarr.ndim

2

In [58]:
myarr.size

12

In [60]:
myarr.dtype

dtype('int32')

In [64]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9],[11,12,13]], dtype='float32')

In [66]:
myarr.dtype

dtype('float32')

In [74]:
n = myarr.astype('float64')

In [76]:
n.dtype

dtype('float64')

In [96]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9],[11,12,13]])

In [98]:
myarr.shape

(4, 3)

In [110]:
reshaped = myarr.reshape((2,6))

In [112]:
reshaped

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 12, 13]])

In [117]:
flat = reshaped.flatten()

In [119]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

# Indexing And Slicing

In [121]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9],[11,12,13]])

In [123]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [125]:
flat[0]

1

In [127]:
flat[3:6]

array([4, 5, 6])

In [129]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [131]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [133]:
b = flat[3:7]

In [135]:
b

array([4, 5, 6, 7])

In [137]:
b[0] = 44444

In [139]:
b

array([44444,     5,     6,     7])

In [141]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          11,    12,    13])

Here B is not a copy, It is a view hence the value in Flat array also changed.<br>
Numpy doesn't make a copy, it refers the same memory location.

How to make copy?


In [147]:
b = flat[3:7].copy()

In [149]:
b

array([44444,     5,     6,     7])

In [151]:
b[0] = 1111

In [153]:
b

array([1111,    5,    6,    7])

In [155]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          11,    12,    13])

In [157]:
flat[[2,6,3]]

array([    3,     7, 44444])

You can do fancy indexing by giving a list of indexes for slicing.

In [160]:
flat[flat > 5]

array([44444,     6,     7,     8,     9,    11,    12,    13])

This is boolean masking.

# Exercise Practice 

In [164]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [166]:
arr.shape

(3, 3)

In [178]:
float_arr = np.array([1.1,2.2,3.3])

In [180]:
float_arr

array([1.1, 2.2, 3.3])

In [188]:
float_arr = np.array((float_arr),dtype = 'int32' )

In [190]:
float_arr

array([1, 2, 3])

In [198]:
fancy = np.array([1,3,5])
array = np.array([1,2,3,4,5,6])

In [200]:
fancy

array([1, 3, 5])

In [202]:
array[fancy]

array([2, 4, 6])

In [204]:
arr = arr.flatten()

In [206]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
arr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [212]:
arr[2] = 100

In [214]:
arr

array([  1,   2, 100,   4,   5,   6,   7,   8,   9])

In [222]:
arr[arr > 50]

array([100])

# Multidimentsional Indexing and Axis

In [34]:
#2D arrays -> Rows and Columns   arr[row, column]

In [12]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])


In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.sum(arr, axis = 0)  #Column Wise

array([12, 15, 18])

In [26]:
np.sum(arr, axis = 1)  #Row Wise

array([ 6, 15, 24])

In [36]:
arr[0, 1]   #Feature of Numpy.

2

In [38]:
arr[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [40]:
#3D arrays -> Depth, Rows and Columns     arr[depth, row, column]

In [44]:
arr3D = np.array([[
    [1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]])

In [46]:
arr3D[0, 1, 2]

6

In [48]:
arr3D[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

# Data types in Numpy

In [51]:
#int32, int64, float32, float64, bool, complex64, object

In [57]:
arr = np.array([23,4,3,23])
arr.dtype

dtype('int32')

In [63]:
arr.astype('float64')

array([23.,  4.,  3., 23.])

In [65]:
arr.dtype

dtype('int32')

In [71]:
arr2 = np.array([23,4,3,23], dtype = 'float32')
arr2.dtype

dtype('float32')

In [80]:
arr.nbytes     #Memory Usage

16

# Broadcasting and Vectorization in Numpy

In [96]:
result = arr ** 2    #Vectorization       Here 2 was broadcasted and no extra memory is used
result

array([529,  16,   9, 529])

In [87]:
# Dimensions must be compatible
# Stretching arrays

In [89]:
# Normalization : When we minus mean, and divide by standard deviation

In [91]:
# normalized_data = (data - mean) / std

# Mathematical Functions in Numpy

In [100]:
np.mean(arr)

13.25

In [102]:
np.std(arr)

9.756408150543928